/***************************************************************************
* PALM++/model library
*
* example/example1.C
*
* $Id$
*
* Copyright (C) 2003 by Matthias Troyer <troyer@itp.phys.ethz.ch>
*
* Permission is hereby granted, free of charge, to any person or organization 
* obtaining a copy of the software covered by this license (the "Software") 
* to use, reproduce, display, distribute, execute, and transmit the Software, 
* and to prepare derivative works of the Software, and to permit others
* to do so for non-commerical academic use, all subject to the following:
*
* The copyright notice in the Software and this entire statement, including 
* the above license grant, this restriction and the following disclaimer, 
* must be included in all copies of the Software, in whole or in part, and 
* all derivative works of the Software, unless such copies or derivative 
* works are solely in the form of machine-executable object code generated by 
* a source language processor.

* In any scientific publication based in part or wholly on the Software, the
* use of the Software has to be acknowledged and the publications quoted
* on the web page http://www.alps.org/license/ have to be referenced.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
* DEALINGS IN THE SOFTWARE.
*
**************************************************************************/

#include <alps/model.h>
#include <iostream>

boost::multi_array<alps::Expression,2> bondmatrix(const alps::ModelLibrary lib, const std::string& name, 
                                                  const alps::Parameters& p=alps::Parameters())
{
  alps::HamiltonianDescriptor<short> ham=lib.hamiltonian(name);
  ham.set_parameters(p);
  int dim=ham.basis().site_basis().num_states();
  
  // get site and bond terms
  boost::multi_array<alps::Expression,2> sitematrix = 
    ham.site_term().matrix<alps::Expression>(ham.basis().site_basis(),lib.simple_operators());
  boost::multi_array<alps::Expression,4> bondtensor = 
    ham.bond_term().matrix<alps::Expression>(ham.basis().site_basis(), ham.basis().site_basis(),lib.simple_operators());
    
  // add site terms to bond terms
  for (int i=0;i<dim;++i)
    for (int j=0;j<dim;++j)
      for (int k=0;k<dim;++k) {
        bondtensor[i][j][i][k]+=sitematrix[j][k];
        bondtensor[j][i][k][i]+=sitematrix[j][k];
      }
      
  //convert tensor into matrix
  boost::multi_array<alps::Expression,2> bondmatrix(boost::extents[dim*dim][dim*dim]);
  for (int i=0;i<dim;++i)
    for (int j=0;j<dim;++j)
      for (int k=0;k<dim;++k)
        for (int l=0;l<dim;++l)
	  bondmatrix[i+j*dim][k+l*dim]=bondtensor[i][j][k][l];
  return bondmatrix;
}

int main()
{

#ifndef BOOST_NO_EXCEPTIONS
  try {
#endif
    // create the library from an XML file
    alps::ModelLibrary lib(std::cin);

    // calculate bond matrices 
    alps::Parameters parms;
    
    std::cout << "HHardcoreBoson = \n" << bondmatrix(lib,"hardcore boson") << "\n\n";
    parms["Nmax"]=2;
    std::cout << "HBoson = \n" << bondmatrix(lib,"boson",parms)  << "\n\n";
    parms["S"]="1/2";
    std::cout << "HSpinHalf = \n" << bondmatrix(lib,"spin")  << "\n\n";
    parms["S"]=1;
    std::cout << "HSpinOne = \n" << bondmatrix(lib,"spin",parms)  << "\n\n";
    

#ifndef BOOST_NO_EXCEPTIONS
}
catch (std::exception& e)
{
  std::cerr << "Caught exception: " << e.what() << "\n";
  exit(-1);
}
catch (...)
{
  std::cerr << "Caught unknown exception\n";
  exit(-2);
}
#endif
}
