/***************************************************************************
* ALPS++/model library
*
* model/sitebasis.h    the basis classes
*
* $Id$
*
* Copyright (C) 2003-2003 by Matthias Troyer <troyer@comp-phys.org>,
*                            Axel Grzesik <axel@th.physik.uni-bonn.de>
*
* Permission is hereby granted, free of charge, to any person or organization 
* obtaining a copy of the software covered by this license (the "Software") 
* to use, reproduce, display, distribute, execute, and transmit the Software, 
* and to prepare derivative works of the Software, and to permit others
* to do so for non-commerical academic use, all subject to the following:
*
* The copyright notice in the Software and this entire statement, including 
* the above license grant, this restriction and the following disclaimer, 
* must be included in all copies of the Software, in whole or in part, and 
* all derivative works of the Software, unless such copies or derivative 
* works are solely in the form of machine-executable object code generated by 
* a source language processor.

* In any scientific publication based in part or wholly on the Software, the
* use of the Software has to be acknowledged and the publications quoted
* on the web page http://www.alps.org/license/ have to be referenced.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
* DEALINGS IN THE SOFTWARE.
*
**************************************************************************/

#ifndef ALPS_MODEL_SITEBASISSTATES_H
#define ALPS_MODEL_SITEBASISSTATES_H

#include <alps/model/quantumnumber.h>
#include <alps/model/sitestate.h>
#include <alps/model/sitebasisdescriptor.h>
#include <vector>
#include <iostream>

namespace alps {

template <class I, class STATE=StateDescriptor<I> >
class SiteBasisStates : public std::vector<STATE>
{
public:
  typedef STATE state_type;
  typedef std::vector<state_type> base_type;
  typedef typename base_type::const_iterator const_iterator;
  typedef typename base_type::value_type value_type;
  typedef typename base_type::size_type size_type;
  SiteBasisStates(const SiteBasisDescriptor<I>& b);
    
  size_type index(const value_type& x) const;
  const SiteBasisDescriptor<I>& basis() const { return basis_;}
  bool check_sort() const;

private:
  SiteBasisDescriptor<I> basis_;
};


// ------------------------------- implementation ----------------------------------

template <class I, class STATE>
typename SiteBasisStates<I,STATE>::size_type SiteBasisStates<I,STATE>::index(const value_type& x) const
{
  const_iterator it = std::lower_bound(begin(),end(),x);
  return (*it==x ? it-begin() : size());
}

template <class I, class STATE>
bool SiteBasisStates<I,STATE>::check_sort() const
{
  for (int i=0;i<size()-1;++i)
    if ((*this)[i]>=(*this)[i+1])
      return false;
  return true;
}

template <class I, class STATE>
SiteBasisStates<I,STATE>::SiteBasisStates(const SiteBasisDescriptor<I>& b)
 : basis_(b)
{
  if (b.num_states()==std::numeric_limits<I>::max())
    boost::throw_exception(std::runtime_error("Cannot build infinite set of basis states\n"));
  std::stack<std::pair<typename SiteBasisDescriptor<I>::const_iterator,half_integer<I> > > s;
  typename SiteBasisDescriptor<I>::const_iterator it=b.begin();
  std::vector<half_integer<I> > quantumnumbers(basis_.size());
  const_cast<QuantumNumber<I>&>(*it).set_parameters(b.get_parameters());
  for(half_integer<I> q=it->max();q>=it->min();--q) 
    s.push(std::make_pair(it,q));
  while(!s.empty()) {
    it=s.top().first;
    quantumnumbers[it-b.begin()]=s.top().second;
    s.pop();
    if(it==b.end()-1) 
      push_back(state_type(quantumnumbers));
    else {
      ++it;
      Parameters p=b.get_parameters();
      for(typename SiteBasisDescriptor<I>::const_iterator qit=b.begin();qit!=it;++qit)
        p[qit->name()]=quantumnumbers[qit-b.begin()];
      const_cast<QuantumNumber<I>&>(*it).set_parameters(p);
      for(half_integer<I> q=it->max();q>=it->min();--q)
        s.push(std::make_pair(it,q));
    }
  }
  if(!check_sort())
    boost::throw_exception(std::logic_error("Site basis not sorted correctly"));
}

}

#ifndef BOOST_NO_OPERATORS_IN_NAMESPACE
namespace alps {
#endif

template <class I, class STATE>
std::ostream& operator<<(std::ostream& out, const alps::SiteBasisStates<I,STATE>& s)
{ 
  out << "{\n";
  for (typename alps::SiteBasisStates<I,STATE>::const_iterator it=s.begin();it!=s.end();++it) {
    out << "  |";
    for (int i=0;i<s.basis().size();++i)
      out << " " << s.basis()[i].name() << "=" << get_quantumnumber(*it,i);
    out << " >\n";
  }
  out << "}\n";
  return out;
}

#ifndef BOOST_NO_OPERATORS_IN_NAMESPACE
} // namespace alps
#endif

#endif
