/***************************************************************************
* PALM++/osiris library
*
* osiris/buffer.C      dumps for object serialization
*
* $Id$
*
* Copyright (C) 1994-2003 by Matthias Troyer <troyer@itp.phys.ethz.ch>,
*                            Synge Todo <wistaria@comp-phys.org>,
*
* Permission is hereby granted, free of charge, to any person or organization 
* obtaining a copy of the software covered by this license (the "Software") 
* to use, reproduce, display, distribute, execute, and transmit the Software, 
* and to prepare derivative works of the Software, and to permit others
* to do so for non-commerical academic use, all subject to the following:
*
* The copyright notice in the Software and this entire statement, including 
* the above license grant, this restriction and the following disclaimer, 
* must be included in all copies of the Software, in whole or in part, and 
* all derivative works of the Software, unless such copies or derivative 
* works are solely in the form of machine-executable object code generated by 
* a source language processor.

* In any scientific publication based in part or wholly on the Software, the
* use of the Software has to be acknowledged and the publications quoted
* on the web page http://www.alps.org/license/ have to be referenced.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
* DEALINGS IN THE SOFTWARE.
*
**************************************************************************/

#include <alps/osiris/buffer.h>
#include <alps/osiris/dump.h>
#include <alps/osiris/std/vector.h>

#include <boost/throw_exception.hpp>
#include <stdexcept>

namespace alps {
namespace detail {

// load Buffer from dump

Buffer::Buffer(IDump& dump)
{
  load(dump);
}

// save the Buffer contents

void Buffer::save(ODump& dump) const
{
  dump << static_cast<const std::vector<uint8_t>&>(*this) << read_pos << write_pos;
}


// load the Buffer contents

void Buffer::load(IDump& dump)
{
  dump >> static_cast<std::vector<uint8_t>&>(*this) >> read_pos >> write_pos;
}


// write a few bytes and update length

void Buffer::write_buffer(const void* p, size_type n)
{
  if(write_pos+n>size())
    resize((((write_pos+n)/buffer_grow_steps)+1)*buffer_grow_steps);
  memcpy(&((*this)[write_pos]),p,n);
  write_pos+=n;
}


// read a few bytes and update position

void Buffer::read_buffer(void* p, size_type n)
{
  if(read_pos+n>size())
    boost::throw_exception(std::runtime_error("read past buffer"));
  memcpy(p,&((*this)[read_pos]),n);
  read_pos+=n;
}

#ifndef BOOST_NO_INCLASS_MEMBER_INITIALIZATION
const Buffer::size_type Buffer::buffer_grow_steps;
#endif
} // end namespace detail
} // end namespace alps
