/***************************************************************************
* PALM++/palm library
*
* palm/os.C
*
* $Id$
*
* Copyright (C) 1994-2002 by Matthias Troyer <troyer@itp.phys.ethz.ch>,
*                            Synge Todo <wistaria@comp-phys.org>,
*
* Permission is hereby granted, free of charge, to any person or organization 
* obtaining a copy of the software covered by this license (the "Software") 
* to use, reproduce, display, distribute, execute, and transmit the Software, 
* and to prepare derivative works of the Software, and to permit others
* to do so for non-commerical academic use, all subject to the following:
*
* The copyright notice in the Software and this entire statement, including 
* the above license grant, this restriction and the following disclaimer, 
* must be included in all copies of the Software, in whole or in part, and 
* all derivative works of the Software, unless such copies or derivative 
* works are solely in the form of machine-executable object code generated by 
* a source language processor.

* In any scientific publication based in part or wholly on the Software, the
* use of the Software has to be acknowledged and the publications quoted
* on the web page http://www.alps.org/license/ have to be referenced.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
* DEALINGS IN THE SOFTWARE.
*
**************************************************************************/

#include <alps/osiris/os.h>

#include <boost/filesystem/operations.hpp>
#include <boost/limits.hpp>
#include <boost/throw_exception.hpp>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <stdexcept>

#include <errno.h>

#ifdef ALPS_HAVE_SYS_TIME_H
# include <sys/time.h>
#endif

#if defined(ALPS_HAVE_SYS_SYSTEMINFO_H)
# include <sys/systeminfo.h> // for sysinfo()
#elif defined(ALPS_HAVE_UNISTD_H)
# include <unistd.h>      // for gethostname()
# ifndef MAXHOSTNAMELEN
#   define MAXHOSTNAMELEN 256
# endif
#endif

#ifdef BOOST_NO_STDC_NAMESPACE
  namespace std { using ::system; }
#endif

namespace alps {
namespace detail {

//=======================================================================
// initialization of global variables contained in global object
//-----------------------------------------------------------------------
class os_variables {
public:
  os_variables();
  double old_clock;
  double clock_offset;
};

extern os_variables the_os_vars;

//=======================================================================
// initialization of global variables contained in global object
//-----------------------------------------------------------------------

os_variables::os_variables()
{
  timeval tp;
  gettimeofday(&tp,0);
  old_clock=tp.tv_sec+1e-6*tp.tv_usec;
  clock_offset=0.;
}

os_variables the_os_vars;

} // end namespace detail


//=======================================================================
// get_host_name
// 
// returns the Host name
//-----------------------------------------------------------------------

std::string hostname()
{
#if defined(ALPS_HAVE_SYS_SYSTEMINFO_H)
  // the UNIX System V version
  char n[256];
  if(sysinfo(SI_HOSTNAME,n,256) < 0)
    boost::throw_exception(std::runtime_error("call to sysinfo failed in get_host_name"));
  return n;
#elif defined(ALPS_HAVE_UNISTD_H)
  // the BSD UNIX version
  char n[MAXHOSTNAMELEN];
  if(gethostname(n,MAXHOSTNAMELEN))
    boost::throw_exception(std::runtime_error("call to gethostname failed in get_host_name"));
  return n;
#else
  // the default version
  return "unnamed";
#endif
}

//=======================================================================
// dclock & dclock_prec
// 
// <dclock> returns the time in seconds, with a precision returned by
// <dclock_prec>. The time can be either CPU time or wallclock time,
// depending on the architecture.
//-----------------------------------------------------------------------

double dclock(void)
{
  timeval tp;
  gettimeofday(&tp,0);
  return tp.tv_sec - detail::the_os_vars.old_clock + 1e-6*tp.tv_usec;
}

double dclock_resolution(void)
{
  return 1./double(CLOCKS_PER_SEC);
}

} // end namespace alps
