language: cpp
sudo: required
dist: trusty

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      # Boost 1.58
      - sourceline: ppa:kzemek/boost
    packages:
      - libboost1.58-dev
      - openmpi-bin
      - openmpi-common
      - openmpi-doc
      - libopenmpi-dev
      - libhdf5-serial-dev

install: true

env:
  - ENABLE_MPI=ON OMPI_CC="$CC" OMPI_CXX="$CXX" CC=mpicc CXX=mpic++
  - ENABLE_MPI=OFF

script:
  # Stop on first error
  - set -e

  # Build ALPSCore
  - mkdir build
  - mkdir install
  - cd build
  - |
    cmake ..                                              \
    -DCMAKE_BUILD_TYPE=Debug                              \
    -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/installed    \
    -DALPS_INSTALL_EIGEN=true                             \
    -DENABLE_MPI=$ENABLE_MPI
  - make -j3
  - make test
  - make install
