/* src/alps/config.h.  Generated by configure.  */
/***************************************************************************
* ALPS++ library
*
* alps/config.h.in
*
* $Id$
*
* Copyright (C) 1994-2003 by Matthias Troyer <troyer@itp.phys.ethz.ch>,
*                            Synge Todo <wistaria@comp-phys.org>,
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
**************************************************************************/

#ifndef ALPS_CONFIG_H
#define ALPS_CONFIG_H

//
// C/C++ headers
//

// Define to 1 if you have the <stdint.h> header file.
#define ALPS_HAVE_STDINT_H 1

// Define to 1 if you have the <inttypes.h> header file.
#define ALPS_HAVE_INTTYPES_H 1

// Define to 1 if you have the <unistd.h> header file.
#define ALPS_HAVE_UNISTD_H 1

// Define to 1 if you have the <bind/bitypes.h> header file.
/* #undef ALPS_HAVE_BIND_BITYPES_H */

// Define to 1 if you have the <sys/int_types.h> header file.
/* #undef ALPS_HAVE_SYS_INT_TYPES_H */

// Define to 1 if you have the <sys/systeminfo.h> header file.
/* #undef ALPS_HAVE_SYS_SYSTEMINFO_H */

// Define to 1 if you have the <sys/time.h> header file.
#define ALPS_HAVE_SYS_TIME_H 1

// Define to 1 if you have the <sys/types.h> header file.
#define ALPS_HAVE_SYS_TYPES_H 1

// Define to 1 if you have valarray<T>.
#define ALPS_HAVE_VALARRAY 1

//
// Libraries
//

// Define to 1 if you have the PTHREAD library
#define ALPS_HAVE_PTHREAD 1

// Define to 1 if you have the MPI library
#define ALPS_HAVE_MPI 1

// Define to 1 if you have the PVM library
/* #undef ALPS_HAVE_PVM */

// Define to 1 if you have the HDF5 library
/* #undef ALPS_HAVE_HDF5 */

//
// XML parser
//

// Define to 1 if you use Expat XML parser by James Clark.
/* #undef ALPS_HAVE_EXPAT_PARSER */

// Define to 1 if you use Xerces C++ XML parser by Apache Software Foundation.
/* #undef ALPS_HAVE_XERCES_PARSER */

//
// Introduce [int,uint]*_t into alps namespace
//

#ifdef ALPS_HAVE_STDINT_H
# include <stdint.h>
#elif defined(ALPS_HAVE_INTTYPES_H)
# include <inttypes.h>
#elif defined(ALPS_HAVE_SYS_INT_TYPES_H)
# include <sys/int_types.h>
#elif defined(ALPS_HAVE_BIND_BITYPES_H)
# include <bind/bitypes.h>
  typedef u_int8_t uint8_t;
  typedef u_int16_t uint16_t;
  typedef u_int32_t uint32_t;
#endif

#include <boost/cstdint.hpp>

namespace alps {

#ifndef BOOST_NO_INT64_T
using boost::int64_t;
using boost::uint64_t;
#endif

} // end namespace alps

#include <boost/config.hpp>

#ifndef BOOST_NO_VOID_RETURNS
# define ALPS_DUMMY_VOID void
# define ALPS_RETURN_VOID
#else
# define ALPS_DUMMY_VOID bool
# define ALPS_RETURN_VOID return true;
#endif

#endif // ALPS_CONFIG_H
