/***************************************************************************
* ALPS++ library
*
* alps/functional.h
*
* $Id$
*
* Copyright (C) 1994-2003 by Matthias Troyer <troyer@itp.phys.ethz.ch>,
*                            Synge Todo <wistaria@comp-phys.org>,
*
* Permission is hereby granted, free of charge, to any person or organization 
* obtaining a copy of the software covered by this license (the "Software") 
* to use, reproduce, display, distribute, execute, and transmit the Software, 
* and to prepare derivative works of the Software, and to permit others
* to do so for non-commerical academic use, all subject to the following:
*
* The copyright notice in the Software and this entire statement, including 
* the above license grant, this restriction and the following disclaimer, 
* must be included in all copies of the Software, in whole or in part, and 
* all derivative works of the Software, unless such copies or derivative 
* works are solely in the form of machine-executable object code generated by 
* a source language processor.

* In any scientific publication based in part or wholly on the Software, the
* use of the Software has to be acknowledged and the publications quoted
* on the web page http://www.alps.org/license/ have to be referenced.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
* DEALINGS IN THE SOFTWARE.
*
**************************************************************************/

#ifndef ALPS_FUNCTIONAL_H
#define ALPS_FUNCTIONAL_H

#include <alps/config.h>
#include <alps/math.hpp>
#include <complex>
#include <functional>

namespace alps {

template <class Arg1, class Arg2=Arg1, class Result=Arg1>
struct plus : std::binary_function<Arg1, Arg2, Result> {
  Result operator () (const Arg1& x, const Arg2& y) const { return x + y; }
};

template <class Arg1, class Arg2=Arg1, class Result=Arg1>
struct minus : std::binary_function<Arg1, Arg2, Result>  {
  Result operator () (const Arg1& x, const Arg2& y) const { return x - y; }
};

template <class Arg1, class Arg2=Arg1, class Result=Arg1>
struct multiplies : std::binary_function<Arg1, Arg2, Result> {
  Result operator () (const Arg1& x, const Arg2& y) const { return x * y; }
};

template <class Arg1, class Arg2=Arg1, class Result=Arg1>
struct divides : std::binary_function<Arg1, Arg2, Result> {
  Result operator () (const Arg1& x, const Arg2& y) const { return x / y; }
};

template <class Arg1, class Arg2=Arg1, class Result=Arg1>
struct modulus : std::binary_function<Arg1, Arg2, Result> {
  Result operator () (const Arg1& x, const Arg2& y) const { return x % y; }
};

template <class Arg1, class Arg2=Arg1, class Result=Arg1>
struct bit_and : std::binary_function<Arg1, Arg2, Result> {
  Result operator () (const Arg1& x, const Arg2& y) const { return x & y; }
};

template <class Arg1, class Arg2=Arg1, class Result=Arg1>
struct bit_or : std::binary_function<Arg1, Arg2, Result> {
  Result operator () (const Arg1& x, const Arg2& y) const { return x | y; }
};

template <class Arg1, class Arg2=Arg1, class Result=Arg1>
struct bit_xor : std::binary_function<Arg1, Arg2, Result> {
  Result operator () (const Arg1& x, const Arg2& y) const { return x ^ y; }
};

template <class T, class X>
struct plus_scaled : std::binary_function<T, T, T> {
    plus_scaled(X x) : val(x) {}
    T operator () (const T& x, const T& y) const { return x + val*y; }
private:
    X val;
};

template <class T, class X>
struct minus_scaled : public std::binary_function<T, T, T> {
    minus_scaled(X x) : val(x) {}
    T operator () (const T& x, const T& y) const { return x - val*y; }
private:
    X val;
};

template <class T>
struct absmax : public std::binary_function<T, T, typename TypeTraits<T>::norm_t> {
    typename TypeTraits<T>::norm_t operator () (const T& x, const T& y) const { return std::max(alps::abs(x),alps::abs(y)); }
};

template <class T>
struct conj_mult : std::binary_function<T,T,T> {
inline T operator()(const T& a, const T& b) const {
  return a*b;
}
};

template <class T>
struct conj_mult<std::complex<T> > : 
  std::binary_function<std::complex<T>,std::complex<T>,std::complex<T> > {
inline std::complex<T> operator()(const std::complex<T>& a, const std::complex<T>& b) const {
  return std::conj(a)*b;
}
};

template<class T> 
struct add_abs : public std::binary_function<T,typename TypeTraits<T>::norm_t,typename TypeTraits<T>::norm_t> {
inline typename TypeTraits<T>::norm_t operator()(typename TypeTraits<T>::norm_t sum, T val) const { return sum+alps::abs(val);}
};

template<class T> 
struct add_abs2 : public std::binary_function<T,typename TypeTraits<T>::norm_t,typename TypeTraits<T>::norm_t> {
inline typename TypeTraits<T>::norm_t operator()(typename TypeTraits<T>::norm_t sum, T val) const { return sum+abs2(val);}
};

}

#endif // ALPS_FUNCTIONAL_H
