/***************************************************************************
* ALPS++ library
*
* alps/parser/parameters.C
*
* $Id$
*
* Copyright (C) 1994-2003 by Matthias Troyer <troyer@itp.phys.ethz.ch>,
*                            Synge Todo <wistaria@comp-phys.org>,
*
* Permission is hereby granted, free of charge, to any person or organization 
* obtaining a copy of the software covered by this license (the "Software") 
* to use, reproduce, display, distribute, execute, and transmit the Software, 
* and to prepare derivative works of the Software, and to permit others
* to do so for non-commerical academic use, all subject to the following:
*
* The copyright notice in the Software and this entire statement, including 
* the above license grant, this restriction and the following disclaimer, 
* must be included in all copies of the Software, in whole or in part, and 
* all derivative works of the Software, unless such copies or derivative 
* works are solely in the form of machine-executable object code generated by 
* a source language processor.

* In any scientific publication based in part or wholly on the Software, the
* use of the Software has to be acknowledged and the publications quoted
* on the web page http://www.alps.org/license/ have to be referenced.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
* DEALINGS IN THE SOFTWARE.
*
**************************************************************************/

#include <alps/parameters.h>
#include <alps/expression.h>
#include <alps/cctype.h>
#include <alps/parser/parser.h>

#include <boost/throw_exception.hpp>
#include <algorithm>
#include <iostream>
#include <stdexcept>

namespace alps {

void Parameters::parse(std::istream& is)
{
  char c;
  do {   
    is >> c;
    if (!is)
      break;
    while (c==';' || c==',') is >> c;  // ignore extra semi-colons  
    if (is && std::isalpha(c)) {
      is.putback(c);
      std::string key = parse_identifier(is);
      std::string value;

      check_character(is, '=', "= expected in assignment while parsing Parameters");

      is >> c;
      switch (c) {
      case '[':
	value = read_until(is, ']');
	break;
      case '"':
	value = read_until(is, '"');
	break;
      case '\'':
	value = read_until(is, '\'');
	break;
      default:                            
	while(c!=';' && c!=',' && c!='}' && c!= '{' && c!='\r' && c!='\n' && is) {
	  value+=c;
	  c = is.get();
	}
	if (c=='{' || c=='}')
	  is.putback(c);
      }
      push_back(key, value, true);
    } else {
      is.putback(c);
      break;
    }
  } while (true);
}

} // namespace alps

//
// XML support
//

#ifndef ALPS_WITHOUT_XML

namespace alps {

ParameterXMLHandler::ParameterXMLHandler(Parameter& p)
  : XMLHandlerBase("PARAMETER"), parameter_(p) {}
  
void ParameterXMLHandler::start_element(const std::string& name,
					const XMLAttributes& attributes)
{
  if (name != "PARAMETER")
    boost::throw_exception(std::runtime_error("ParameterXMLHandler: unknown tag name : " + name));
  if (!attributes.defined("name"))
    boost::throw_exception(std::runtime_error("ParameterXMLHandler: name attribute not found in PARAMETER tag"));
  parameter_.key() = attributes["name"];
}

void ParameterXMLHandler::end_element(const std::string&) {}

void ParameterXMLHandler::text(const std::string& text) {
  parameter_.value() = text;
}
  
ParametersXMLHandler::ParametersXMLHandler(Parameters& p)
  : CompositeXMLHandler("PARAMETERS"), parameters_(p), parameter_(),
    handler_(parameter_)
{
  add_handler(handler_);
}

void ParametersXMLHandler::start_child(const std::string&,
				       const XMLAttributes&)
{
  parameter_ = Parameter();
}

void ParametersXMLHandler::end_child(const std::string&)
{
  parameters_.operator[](parameter_.key()) = parameter_.value();
}
 
} // namespace alps

#endif // !ALPS_WITHOUT_XML
