/***************************************************************************
* ALPS++/lattice library
*
* lattice/vectorio.h     XML parser for lattices
*
* $Id$
*
* Copyright (C) 2001-2003 by Matthias Troyer <troyer@itp.phys.ethz.ch>
*                            Synge Todo <wistaria@comp-phys.org>
*
* Permission is hereby granted, free of charge, to any person or organization 
* obtaining a copy of the software covered by this license (the "Software") 
* to use, reproduce, display, distribute, execute, and transmit the Software, 
* and to prepare derivative works of the Software, and to permit others
* to do so for non-commerical academic use, all subject to the following:
*
* The copyright notice in the Software and this entire statement, including 
* the above license grant, this restriction and the following disclaimer, 
* must be included in all copies of the Software, in whole or in part, and 
* all derivative works of the Software, unless such copies or derivative 
* works are solely in the form of machine-executable object code generated by 
* a source language processor.

* In any scientific publication based in part or wholly on the Software, the
* use of the Software has to be acknowledged and the publications quoted
* on the web page http://www.alps.org/license/ have to be referenced.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
* DEALINGS IN THE SOFTWARE.
*
**************************************************************************/

#ifndef ALPS_VECTORIO_H
#define ALPS_VECTORIO_H

#include <alps/config.h>
#include <alps/parser/parser.h>
#include <alps/vectortraits.h>

#include <boost/throw_exception.hpp>
#include <iostream>
#include <string>
#ifndef BOOST_NO_STRINGSTREAM
# include <sstream>
#else
# include <strstream>
# define istringstream istrstream
#endif
#include <stdexcept>

namespace alps {

template <class CONTAINER>
inline void read_vector_resize (std::istream& in, CONTAINER& v)
{
  typedef typename VectorTraits<CONTAINER>::value_type value_type;
  std::vector<value_type> tmp;
  while(true) {
    value_type x;
    in >> x;
    if (!in)
      break;
    tmp.push_back(x);
  }
  vectorops::resize(v,tmp.size());
  for (int i=0;i<vectorops::size(v);++i)
    v[i]=tmp[i];
}

template <class CONTAINER>
inline void read_vector (std::istream& in, CONTAINER& v)
{
  typename VectorTraits<CONTAINER>::size_type i=0;
  while (i!=vectorops::size(v))
    in >> v[i++];
}

template <class CONTAINER>
inline void read_vector (std::istream& in, CONTAINER& v, 
         typename VectorTraits<CONTAINER>::size_type dim)
{
  vectorops::resize(v,dim);
  read_vector(in,v);
}

template <class CONTAINER>
inline void read_vector (const std::string& s, CONTAINER& v,
         typename VectorTraits<CONTAINER>::size_type dim)
{
  std::istringstream in(s.c_str());
  read_vector(in,v,dim);
}

template <class CONTAINER>
inline void read_vector (const std::string& s, CONTAINER& v)
{
  std::istringstream in(s.c_str());
  read_vector(in,v);
}

template <class CONTAINER>
inline void read_vector_resize (const std::string& s, CONTAINER& v)
{
  std::istringstream in(s.c_str());
  read_vector_resize(in,v);
}

template <class CONTAINER>
inline CONTAINER read_vector (const std::string& s,
         typename VectorTraits<CONTAINER>::size_type dim)
{
  CONTAINER v;
  read_vector(s,v,dim);
  return v;
}

template <class CONTAINER>
inline CONTAINER read_vector (const std::string& s)
{
  CONTAINER v;
  read_vector(s,v);
  return v;
}

template <class CONTAINER>
inline CONTAINER read_vector (std::istream& in,
         typename VectorTraits<CONTAINER>::size_type dim)
{
  CONTAINER v;
  read_vector(in,v,dim);
  return v;
}

template <class CONTAINER>
inline CONTAINER read_vector (std::istream& in)
{
  CONTAINER v;
  read_vector(in,v);
  return v;
}

template <class CONTAINER>
inline void write_vector(std::ostream& out, const CONTAINER& v)
{
  for (std::size_t i=0;i<vectorops::size(v);++i) {
    out << v[i];
    if (i!=vectorops::size(v)-1)
      out << " ";
  }
}

template <class CONTAINER>
class vector_writer_t
{
public:
  vector_writer_t(const CONTAINER& c) : c_(c) {}
  void write(std::ostream& out) const {write_vector(out,c_);}
private:
  const CONTAINER& c_;
};

template <class CONTAINER>
inline vector_writer_t<CONTAINER> vector_writer(const CONTAINER& c)
{
  return vector_writer_t<CONTAINER>(c);
}

} // end namespace lattice

#ifndef BOOST_NO_OPERATORS_IN_NAMESPACE
namespace alps {
#endif

template <class CONTAINER>
inline std::ostream& operator<<(std::ostream& out,
				const alps::vector_writer_t<CONTAINER>& w)
{
  w.write(out);
  return out;
}

#ifndef BOOST_NO_OPERATORS_IN_NAMESPACE
} // namespace alps
#endif

#endif // ALPS_VECTORIO_H
