/***************************************************************************
* PALM++/alea library
*
* alea/simpleobseval.C    simple example program for observable evaluator
*
* $Id$
*
* Copyright (C) 1994-2003 by Matthias Troyer <troyer@itp.phys.ethz.ch>,
*                            Synge Todo <wistaria@comp-phys.org>,
*
* Permission is hereby granted, free of charge, to any person or organization 
* obtaining a copy of the software covered by this license (the "Software") 
* to use, reproduce, display, distribute, execute, and transmit the Software, 
* and to prepare derivative works of the Software, and to permit others
* to do so for non-commerical academic use, all subject to the following:
*
* The copyright notice in the Software and this entire statement, including 
* the above license grant, this restriction and the following disclaimer, 
* must be included in all copies of the Software, in whole or in part, and 
* all derivative works of the Software, unless such copies or derivative 
* works are solely in the form of machine-executable object code generated by 
* a source language processor.

* In any scientific publication based in part or wholly on the Software, the
* use of the Software has to be acknowledged and the publications quoted
* on the web page http://www.alps.org/license/ have to be referenced.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
* DEALINGS IN THE SOFTWARE.
*
**************************************************************************/

#include <alps/alea.h>
#include <boost/random.hpp> 
#include <iostream>
#include <iomanip>

int main()
{
#ifndef BOOST_NO_EXCEPTIONS
try {
#endif
  // std::cout << std::setprecision(10);

  //DEFINE RANDOM NUMBER GENERATOR
  //------------------------------
  typedef boost::minstd_rand0 random_base_type;
  typedef boost::uniform_01<random_base_type> random_type; 
  random_base_type random_int;
  random_type random(random_int); 

  //DEFINE OBSERVABLES
  //------------------
  alps::RealObservable obs_a("observable a");
  alps::RealObservable obs_b("observable b");
  alps::RealObservable obs_c("observable c");
  obs_a.reset(true);
  obs_b.reset(true);
  obs_c.reset(true);

  for(int i=0; i < (1<<12); ++i) {
    obs_a << random();
    obs_b << random()+1;
    obs_c << random()+1 << random()+1 << random()+1;
  }

  std::cout << obs_a;
  std::cout << obs_b;
  std::cout << obs_c;

  //JACKKNIVE ANALYSIS
  //------------------

  std::cout << "Jackknife analysis\n";

  alps::RealObsevaluator obseval_a(obs_a);
  std::cout << obseval_a;
  std::cout << "  count = " << obseval_a.count()
	    << ", bin size = " << obseval_a.bin_size()
	    << ", number of bins = " << obseval_a.bin_number()
	    << std::endl;

  alps::RealObsevaluator obseval_b(obs_b);
  std::cout << obseval_b;
  std::cout << "  count = " << obseval_b.count()
	    << ", bin size = " << obseval_b.bin_size()
	    << ", number of bins = " << obseval_b.bin_number()
	    << std::endl;
  alps::RealObsevaluator obseval_c(obs_c);
  std::cout << obseval_c;
  std::cout << "  count = " << obseval_c.count()
	    << ", bin size = " << obseval_c.bin_size()
	    << ", number of bins = " << obseval_c.bin_number()
	    << std::endl;

  std::cout << "five different methods to construct RealObsevaluator\n";

  alps::RealObsevaluator obseval_0 = obseval_b / obseval_a;
  std::cout << "  " << obseval_0;

  alps::RealObsevaluator obseval_1(obseval_b / obseval_a);
  std::cout << "  " << obseval_1;

  alps::RealObsevaluator obseval_2(obseval_b / obseval_a, "obseval_e");
  std::cout << "  " << obseval_2;

  alps::RealObsevaluator obseval_3("obseval_f");
  obseval_3 = (obseval_b / obseval_a);
  std::cout << "  " << obseval_3;

  alps::RealObsevaluator obseval_4("obseval_g");
  obseval_4 << (obseval_b / obseval_a);
  std::cout << "  " << obseval_4;

  std::cout << "  count = " << obseval_4.count()
	    << ", bin size = " << obseval_4.bin_size()
	    << ", number of bins = " << obseval_4.bin_number()
	    << std::endl;

  std::cout << "merging observables b and c\n";
  alps::RealObsevaluator obseval_5("obseval_5");
  obseval_5 << obseval_b << obseval_c;
  std::cout << "  " << obseval_5;
  std::cout << "  count = " << obseval_5.count()
	    << ", bin size = " << obseval_5.bin_size()
	    << ", number of bins = " << obseval_5.bin_number()
	    << std::endl;
  
  alps::RealObsevaluator obseval_h = 1.0 / obseval_a;
  std::cout << obseval_h;

  alps::RealObsevaluator obseval_i = 1.0 / obseval_b;
  std::cout << obseval_i;

#ifndef BOOST_NO_EXCEPTIONS
}
catch (std::exception& exc) {
  std::cerr << exc.what() << "\n";
  return -1;
}
catch (...) {
  std::cerr << "Fatal Error: Unknown Exception!\n";
  return -2;
}
#endif
}

