/***************************************************************************
* ALPS++/scheduler library
*
* scheduler/modelplugin.h
*
* $Id$
*
* Copyright (C) 1994-2003 by Matthias Troyer <troyer@itp.phys.ethz.ch>,
*
* Permission is hereby granted, free of charge, to any person or organization 
* obtaining a copy of the software covered by this license (the "Software") 
* to use, reproduce, display, distribute, execute, and transmit the Software, 
* and to prepare derivative works of the Software, and to permit others
* to do so for non-commerical academic use, all subject to the following:
*
* The copyright notice in the Software and this entire statement, including 
* the above license grant, this restriction and the following disclaimer, 
* must be included in all copies of the Software, in whole or in part, and 
* all derivative works of the Software, unless such copies or derivative 
* works are solely in the form of machine-executable object code generated by 
* a source language processor.

* In any scientific publication based in part or wholly on the Software, the
* use of the Software has to be acknowledged and the publications quoted
* on the web page http://www.alps.org/license/ have to be referenced.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
* DEALINGS IN THE SOFTWARE.
*
**************************************************************************/

#ifndef ALPS_SCHEDULER_MODELPLUGIN_H
#define ALPS_SCHEDULER_MODELPLUGIN_H

#include <alps/model.h>

namespace alps {
namespace scheduler {

class ModelPlugin
{
public:  
  ModelPlugin(alps::Parameters& p) // it updates the parameter object passed to it!
   : model_library_(p), 
     model_(model_library_.hamiltonian(p["MODEL"])) 
  {
    p.copy_undefined(model_.default_parameters());
    model_.set_parameters(p);
  }
  
  const ModelLibrary::OperatorDescriptorMap& simple_operators() const { 
    return model_library_.simple_operators();
  }
  
  HamiltonianDescriptor<short>& model() { return model_;}
  const HamiltonianDescriptor<short>& model() const { return model_;}
   
private:
   ModelLibrary model_library_;
   HamiltonianDescriptor<short> model_;
};

} // end namespace
} // end namespace

#endif
