/***************************************************************************
* ALPS++/alps library
*
* alps/signal.C      dumps for object serialization
*
* $Id$
*
* Copyright (C) 1994-2003 by Matthias Troyer <troyer@itp.phys.ethz.ch>,
*                            Synge Todo <wistaria@comp-phys.org>,
*
* Permission is hereby granted, free of charge, to any person or organization 
* obtaining a copy of the software covered by this license (the "Software") 
* to use, reproduce, display, distribute, execute, and transmit the Software, 
* and to prepare derivative works of the Software, and to permit others
* to do so for non-commerical academic use, all subject to the following:
*
* The copyright notice in the Software and this entire statement, including 
* the above license grant, this restriction and the following disclaimer, 
* must be included in all copies of the Software, in whole or in part, and 
* all derivative works of the Software, unless such copies or derivative 
* works are solely in the form of machine-executable object code generated by 
* a source language processor.

* In any scientific publication based in part or wholly on the Software, the
* use of the Software has to be acknowledged and the publications quoted
* on the web page http://www.alps.org/license/ have to be referenced.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
* DEALINGS IN THE SOFTWARE.
*
**************************************************************************/

// TODO: signals sent by a message
 
#include <alps/scheduler/signal.hpp>

#include <boost/throw_exception.hpp>
#include <iostream>
#include <signal.h>
#include <stdexcept>
#ifdef ALPS_HAVE_UNISTD_H
# include <unistd.h>
#endif
#ifdef ALPS_HAVE_SYS_TYPES_H
# include <sys/types.h>
#endif

namespace alps {
namespace scheduler {

//=======================================================================
// static member objects
//-----------------------------------------------------------------------

unsigned int SignalHandler::u1; // number of user1 signals received
unsigned int SignalHandler::u2; // number of user2 signals received
unsigned int SignalHandler::k; // number of terminate signals received
unsigned int SignalHandler::s; // number of stop signals received
unsigned int SignalHandler::count; // total number of signals received
bool SignalHandler::initialized=false; 

extern "C" {
  typedef void (*signal_handle_ptr)(int i);
}

SignalHandler::SignalHandler()
{
  if(!initialized)
    {
      initialized=true;
      u1=u2=k=s=count=0;
	  
      // register the signal handlers
      signal(SIGINT, reinterpret_cast<signal_handle_ptr>(&kill));
      signal(SIGTERM, reinterpret_cast<signal_handle_ptr>(&kill));
      signal(SIGQUIT, reinterpret_cast<signal_handle_ptr>(&kill));
      signal(SIGTSTP, reinterpret_cast<signal_handle_ptr>(&tstp));
      signal(SIGUSR1, reinterpret_cast<signal_handle_ptr>(&usr1));
      signal(SIGUSR1, reinterpret_cast<signal_handle_ptr>(&usr2));
    }
}


// functions to be called if signals are intercepted

void SignalHandler::kill(int)
{
  if(!k)
    {
      count++;
      k++;
    }
}

void SignalHandler::usr1(int)
{
  if(!u1)
    {
      count++;
      u1++;
    }
}


void SignalHandler::usr2(int)
{
  if(!u2)
    {
      count++;
      u2++;
    }
}


void SignalHandler::tstp(int)
{
  if(!s)
    {
      count++;
      s++;
    }
}


// stop this Process

void SignalHandler::stopprocess()
{
  ::kill(getpid(),SIGSTOP); // stop myself
}  


// check for a signal

SignalHandler::SignalInfo SignalHandler::operator() ()
{
  if(!count)
    {
        return NOSIGNAL;
     }
  
  if(u1)
    {
      count--;
      u1--;
      return USER1; // has highest priority
    }
    
  if(u2)
    {
      count--;
      u2--;
      return USER2; // has 2nd highest priority
    }

  if(s)
    {
      count--;
      s--;
      return STOP; // 3rd highest priority
    }
    
  if(k)
     {
      count--;
      k--;
      return TERMINATE; // only after all other signals have been processed
    }
    
  boost::throw_exception(std::logic_error("total number of signals does not match sum in SignalHandler"));
  return TERMINATE;
}

} // namespace scheduler
} // namespace alps
