/***************************************************************************
* ALPS++/scheduler library
*
* scheduler/task.C   A class to store parameters
*
* $Id$
*
* Copyright (C) 2003 by Matthias Troyer <troyer@comp-phys.org>
*
* Permission is hereby granted, free of charge, to any person or organization 
* obtaining a copy of the software covered by this license (the "Software") 
* to use, reproduce, display, distribute, execute, and transmit the Software, 
* and to prepare derivative works of the Software, and to permit others
* to do so for non-commerical academic use, all subject to the following:
*
* The copyright notice in the Software and this entire statement, including 
* the above license grant, this restriction and the following disclaimer, 
* must be included in all copies of the Software, in whole or in part, and 
* all derivative works of the Software, unless such copies or derivative 
* works are solely in the form of machine-executable object code generated by 
* a source language processor.

* In any scientific publication based in part or wholly on the Software, the
* use of the Software has to be acknowledged and the publications quoted
* on the web page http://www.alps.org/license/ have to be referenced.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
* DEALINGS IN THE SOFTWARE.
*
**************************************************************************/

#include <alps/scheduler/task.h>
#include <alps/scheduler/types.h>
#include <alps/scheduler/scheduler.h>
#include <alps/expression.h>
#include <alps/osiris.h>
#include <alps/parser/parser.h>

#include <boost/filesystem/operations.hpp>
#include <boost/filesystem/fstream.hpp>
#include <boost/throw_exception.hpp>
#include <fstream>
#include <stdexcept>

namespace alps {
namespace scheduler {


static void Task::print_copyright(std::ostream& out) 
{
  out << "Non-copyrighted program. Please insert your own copyright statement by overwriting the print_copyright static member function of your Task class.\n";
}


Task::Task(const ProcessList& w,const boost::filesystem::path& filename)
  : AbstractTask(w),
    infilename(filename),
    started_(false),
    finished_(false)
{
  parse_task_file(true);
}

Task::~Task()
{
}

void Task::parse_task_file(bool read_parms_only)
{
  boost::filesystem::ifstream infile(infilename);
  
  // read outermost tag (e.g. <SIMULATION>)
  XMLTag tag=parse_tag(infile,true);
  std::string closingtag = "/"+tag.name;
  
  // scan for <PARAMETERS> and read them
  tag=parse_tag(infile,true);
  while (tag.name!="PARAMETERS" && tag.name != closingtag) {
    skip_element(infile,tag);
    tag=parse_tag(infile,true);
  }
  parms.read_xml(tag,infile,true);
  if (!parms.defined("SEED"))
    parms["SEED"]=0;
  if (!read_parms_only) {
    // scan for first worker element (e.g. <MCRUN> or <REALIZATION>)
    tag=parse_tag(infile,true);
    while (tag.name != closingtag) {
      handle_tag(infile,tag);
      tag=parse_tag(infile,true);
    }
  }
}

void Task::handle_tag(std::istream& infile, const XMLTag& tag) 
{
  skip_element(infile,tag);
}

void Task::construct() // delayed until child class is fully constructed
{
  parse_task_file();
}
        
	
// start all runs which are active
void Task::start()
{
  started_=true;
}

void Task::run()
{
  if(started())
    dostep();
}

// start an extra run on a new node
void Task::add_process(const Process& p)
{
  boost::throw_exception(std::runtime_error("Cannot add a process to a single process task"));
}


// remove one run : hope that a checkpoint was created before!!!
void Task::delete_process(const Process& p)
{
  boost::throw_exception(std::runtime_error("Cannot delete a process from a single process task"));
}


// is it finished???
bool Task::finished(double& more_time) const
{
  return finished_;
}

void Task::finish() 
{
  finished_=true;
}

// halt all active runs
void Task::halt()
{
  started_=false;
}


double Task::work() const
{
  return (finished_ ? 0. : (parms.defined("WORK_FACTOR") ? evaluate(parms["WORK_FACTOR"], parms) : 1. ));
}

void Task::write_xml_header(oxstream& out) const
{
  out << header("UTF-8") << stylesheet(xslt_path("ALPS.xsl"));
  out << start_tag("SIMULATION") << xml_namespace("xsi","http://www.w3.org/2001/XMLSchema-instance")
      << attribute("xsi:noNamespaceSchemaLocation","http://xml.comp-phys.org/2002/10/ALPS.xsd");
}


void Task::write_xml_trailer(oxstream& out) const
{
  out << end_tag("SIMULATION");
}

// checkpoint: save into a file
void Task::checkpoint(const boost::filesystem::path& fn) const
{
  boost::filesystem::path dir=fn.branch_path();
  bool make_backup = boost::filesystem::exists(fn);
  boost::filesystem::path filename = (make_backup ? dir/(fn.leaf()+".bak") : fn);
  {
  alps::oxstream out (filename);
  write_xml_header(out);
  out << parms;
  write_xml_body(out,fn);
  write_xml_trailer(out);
  } // close file
  if(make_backup) {
    boost::filesystem::remove(fn);
    boost::filesystem::rename(filename,fn);
  }
}


} // namespace scheduler
} // namespace alps
