/***************************************************************************
* PALM++/xml library
*
* xml/xmlhandler.C   XML handler abstract class
*
* $Id$
*
* Copyright (C) 2001-2003 by Matthias Troyer <troyer@itp.phys.ethz.ch>,
*                            Synge Todo <wistaria@comp-phys.org>,
*
* Permission is hereby granted, free of charge, to any person or organization 
* obtaining a copy of the software covered by this license (the "Software") 
* to use, reproduce, display, distribute, execute, and transmit the Software, 
* and to prepare derivative works of the Software, and to permit others
* to do so for non-commerical academic use, all subject to the following:
*
* The copyright notice in the Software and this entire statement, including 
* the above license grant, this restriction and the following disclaimer, 
* must be included in all copies of the Software, in whole or in part, and 
* all derivative works of the Software, unless such copies or derivative 
* works are solely in the form of machine-executable object code generated by 
* a source language processor.

* In any scientific publication based in part or wholly on the Software, the
* use of the Software has to be acknowledged and the publications quoted
* on the web page http://www.alps.org/license/ have to be referenced.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
* DEALINGS IN THE SOFTWARE.
*
**************************************************************************/

#include <alps/parser/xmlhandler.h>

namespace alps {

void CompositeXMLHandler::add_handler(XMLHandlerBase& handler) {
  if (handlers_.find(handler.basename()) != handlers_.end())
    boost::throw_exception(std::invalid_argument("XMLHandlerSet: duplicated handler for tag : " + handler.basename()));
  handlers_[handler.basename()] = &handler;
}
bool CompositeXMLHandler::has_handler(const XMLHandlerBase& handler) const {
  return handlers_.find(handler.basename()) != handlers_.end();
}
bool CompositeXMLHandler::has_handler(const std::string& name) const {
  return handlers_.find(name) != handlers_.end();
}
  
void CompositeXMLHandler::start_element(const std::string& name,
  const XMLAttributes& attributes) {
  if (level_ == 0) {
    if (name != basename())
      boost::throw_exception(std::runtime_error("XMLCompositeHandler: unknown start tag : " + name));
    start_top(name, attributes);
  } else if (level_ == 1) {
    if (start_element_impl(name, attributes) == false) {
      map_type::const_iterator h = handlers_.find(name);
      if (h == handlers_.end())
	boost::throw_exception(std::runtime_error("XMLCompositeHandler: unknown start tag : " + name));
      start_child(name, attributes);
      current_ = h->second;
      current_->start_element(name, attributes);
    }
  } else {
    if (current_ == 0) {
      if (start_element_impl(name, attributes) == false) {
	boost::throw_exception(std::runtime_error("XMLCompositeHandler: unknown start tag : " + name));
      }
    } else {
      current_->start_element(name, attributes);
    }
  }
  ++level_;
}
void CompositeXMLHandler::end_element(const std::string& name) {
  if (level_ == 1) {
    end_top(name);
  } else {
    if (current_ == 0) {
      if (end_element_impl(name) == false)
	boost::throw_exception(std::runtime_error("XMLCompositeHandler: unknown end tag : " + name));
    } else {
      current_->end_element(name);
      if (level_ == 2) {
	end_child(name);
	current_ = 0;
      }
    }
  }
  --level_;
}
void CompositeXMLHandler::text(const std::string& text) {
  if (current_ == 0) {
    if (text_impl(text) == false)
      boost::throw_exception(std::runtime_error("XMLCompositeHandler: text is not allowed here"));
  } else {
    current_->text(text);
  }
}
  
} // namespace alps
