/***************************************************************************
* PALM++/lattice library
*
* lattice/propertymap.h    some useful property maps for graphs
*
* $Id$
*
* Copyright (C) 2003-2003 by Matthias Troyer <troyer@comp-phys.org>
*
* Permission is hereby granted, free of charge, to any person or organization 
* obtaining a copy of the software covered by this license (the "Software") 
* to use, reproduce, display, distribute, execute, and transmit the Software, 
* and to prepare derivative works of the Software, and to permit others
* to do so for non-commerical academic use, all subject to the following:
*
* The copyright notice in the Software and this entire statement, including 
* the above license grant, this restriction and the following disclaimer, 
* must be included in all copies of the Software, in whole or in part, and 
* all derivative works of the Software, unless such copies or derivative 
* works are solely in the form of machine-executable object code generated by 
* a source language processor.

* In any scientific publication based in part or wholly on the Software, the
* use of the Software has to be acknowledged and the publications quoted
* on the web page http://www.alps.org/license/ have to be referenced.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
* DEALINGS IN THE SOFTWARE.
*
**************************************************************************/

#ifndef PALM_LATTICE_PROPERTYMAP_H
#define PALM_LATTICE_PROPERTYMAP_H

#include <boost/property_map.hpp>
#include <boost/graph/properties.hpp>

namespace alps {

template <class V> // singleton_property_map and constant_property_map
class singleton_property_map {
public:
  typedef std::size_t key_type;
  typedef V value_type;
  typedef V& reference;
  typedef boost::lvalue_property_map_tag category;

  singleton_property_map(V v=V()) : v_(v) {}

  operator V () const { return v_;}

  const singleton_property_map<V>& operator=(const V& v) { v_=v; return *this;}

  template <class T>
  V& operator[](T ) { return v_;}

  template <class T>
  const V& operator[](T ) const { return v_;}
private:
  V v_;
};


template <class Container, class Graph, class Property>
struct container_property_map
{
  typedef typename Container::value_type value_type;
  typedef typename Container::reference reference;
  typedef typename Container::const_reference const_reference;
  typedef typename Container::iterator iterator;
  typedef typename Container::const_iterator const_iterator;
  typedef typename boost::property_map<Graph,Property>::const_type 
                     index_map_type;
  typedef boost::iterator_property_map<iterator, index_map_type,
              value_type, reference> type;
  typedef boost::iterator_property_map<const_iterator, index_map_type,
              value_type, const_reference> const_type;
};

template <class Container, class Graph, class Property>
typename container_property_map<Container,Graph,Property>::type
make_container_property_map(Container& c, const Graph& g, Property p)
{
  return typename container_property_map<Container,Graph,Property>::type
    (c.begin(),boost::get(p,g));
}

template <class Container, class Graph, class Property>
typename container_property_map<Container,Graph,Property>::const_type
make_const_container_property_map(Container& c, const Graph& g, Property p)
{
  return typename container_property_map<Container,Graph,Property>::type
    (c.begin(),boost::get(p,g));
}

} // end namespace alps

#endif

